@php
    $isBangla = $locale === 'bn';
    $title = $isBangla ? $page['bn_title'] : $page['title'];
    $description = $isBangla ? $page['bn_description'] : $page['description'];
    $intro = $isBangla ? $page['bn_intro'] : $page['intro'];
    $benefits = $isBangla ? $page['bn_benefits'] : $page['benefits'];
    $faqs = $isBangla ? $page['bn_faqs'] : $page['faqs'];
    $canonical = route($isBangla ? 'seo.bn.'.$slug : 'seo.'.$slug);
@endphp
<!doctype html>
<html lang="{{ $isBangla ? 'bn' : 'en' }}">
<head>
    <meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="{{ $description }}"><meta name="theme-color" content="#071229">
    <link rel="canonical" href="{{ $canonical }}">
    <link rel="alternate" hreflang="en" href="{{ route('seo.'.$slug) }}">
    <link rel="alternate" hreflang="bn" href="{{ route('seo.bn.'.$slug) }}">
    <link rel="alternate" hreflang="x-default" href="{{ route('seo.'.$slug) }}">
    <link rel="icon" type="image/svg+xml" href="{{ asset('images/bizzsmart-logo.svg') }}">
    <title>{{ $title }} | BizzSmart</title>
    <style>
        :root{--navy:#071229;--blue:#5c73ef;--teal:#34bda0;--ink:#15213b;--muted:#69758b;--line:#e7ebf2}*{box-sizing:border-box}body{margin:0;color:var(--ink);font-family:Arial,sans-serif;background:#fbfcff}a{color:inherit}.wrap{width:min(1120px,calc(100% - 36px));margin:auto}.top{background:var(--navy);color:#fff;padding:18px 0}.top-in{display:flex;align-items:center;justify-content:space-between;gap:20px}.brand{display:flex;align-items:center;gap:9px;text-decoration:none;font-size:21px;font-weight:800}.brand img{width:34px;height:34px}.brand span span{color:#7286ff}.nav{display:flex;align-items:center;gap:18px;font-size:13px;color:#b8c3db}.nav a{text-decoration:none}.nav .btn,.btn{background:var(--blue);color:#fff;border:0;border-radius:7px;padding:11px 16px;text-decoration:none;font-weight:700}.hero{background:linear-gradient(120deg,#071229,#162d64);color:#fff;padding:76px 0 82px}.eyebrow{font-size:11px;letter-spacing:2px;text-transform:uppercase;color:#91a7ff;font-weight:700}.hero h1{font-size:clamp(35px,5vw,58px);line-height:1.08;letter-spacing:-2px;max-width:800px;margin:14px 0 18px}.hero p{max-width:730px;color:#c5cee1;font-size:18px;line-height:1.7;margin:0}.hero-actions{display:flex;gap:12px;flex-wrap:wrap;margin-top:30px}.hero .outline{border:1px solid #7183b5;background:transparent}.section{padding:72px 0}.section h2{font-size:34px;letter-spacing:-1px;margin:0 0 13px}.section-lead{color:var(--muted);line-height:1.7;max-width:750px}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:16px;margin-top:30px}.card{background:#fff;border:1px solid var(--line);border-radius:13px;padding:24px;box-shadow:0 12px 35px #0b17330b}.card h3{font-size:18px;margin:0 0 9px}.card p,.card li{color:var(--muted);font-size:14px;line-height:1.65}.card ul{padding-left:18px;margin-bottom:0}.split{display:grid;grid-template-columns:1.1fr .9fr;gap:30px;align-items:center}.shot{background:#101d3c;border-radius:16px;padding:15px;box-shadow:0 22px 55px #0712292e}.shot img{display:block;width:100%;border-radius:8px}.quote{background:#eef1ff;border-left:4px solid var(--blue);padding:19px 22px;border-radius:8px;color:#2d3d72;line-height:1.7}.quote small{display:block;margin-top:10px;color:#6e7a95}.faq{border-top:1px solid var(--line);padding:18px 0}.faq h3{font-size:16px;margin:0 0 8px}.faq p{color:var(--muted);line-height:1.65;margin:0}.bottom-cta{background:#071229;color:#fff;padding:60px 0}.bottom-cta h2{margin:0 0 12px}.bottom-cta p{color:#b9c4db;line-height:1.6}.footer{padding:24px 0;color:#7d899f;font-size:12px;border-top:1px solid var(--line)}@media(max-width:760px){.nav a:not(.btn){display:none}.grid,.split{grid-template-columns:1fr}.hero{padding:58px 0}.section{padding:55px 0}}
    </style>
    <script type="application/ld+json">{!! json_encode([
        "\x40context" => 'https://schema.org',
        "\x40graph" => [
            ["\x40type"=>'Organization',"\x40id"=>url('/').'#organization','name'=>'BizzSmart','url'=>url('/'),'logo'=>asset('images/bizzsmart-logo.svg'),'email'=>'contact@bizzsmart.xyz','telephone'=>'+8801976729816'],
            ["\x40type"=>'SoftwareApplication','name'=>'BizzSmart ERP','applicationCategory'=>'BusinessApplication','operatingSystem'=>'Web, Android','description'=>$description,'url'=>$canonical,'publisher'=>["\x40id"=>url('/').'#organization']],
            ["\x40type"=>'Product','name'=>'BizzSmart ERP','brand'=>["\x40type"=>'Brand','name'=>'BizzSmart'],'description'=>$description,'url'=>$canonical],
            ["\x40type"=>'FAQPage','mainEntity'=>array_map(fn($faq)=>["\x40type"=>'Question','name'=>$faq['q'],'acceptedAnswer'=>["\x40type"=>'Answer','text'=>$faq['a']]],$faqs)],
        ],
    ], JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE) !!}</script>
</head>
<body>
    <header class="top"><div class="wrap top-in"><a class="brand" href="{{ route('home') }}"><img src="{{ asset('images/bizzsmart-logo.svg') }}" alt="BizzSmart"><span>Bizz<span>Smart</span></span></a><nav class="nav"><a href="{{ route('home') }}#features">Features</a><a href="{{ route('home') }}#solutions">Solutions</a><a href="{{ route('home') }}#contact">Contact</a><a href="{{ $isBangla ? route('seo.'.$slug) : route('seo.bn.'.$slug) }}">{{ $isBangla ? 'English' : 'বাংলা' }}</a><a class="btn" href="{{ route('home') }}#contact">{{ $isBangla ? 'ডেমো চাই' : 'Book a demo' }} ↗</a></nav></div></header>
    <main>
        <section class="hero"><div class="wrap"><div class="eyebrow">BizzSmart ERP · {{ $isBangla ? 'বাংলাদেশের ব্যবসার জন্য' : 'Built for Bangladesh businesses' }}</div><h1>{{ $title }}</h1><p>{{ $intro }}</p><div class="hero-actions"><a class="btn" href="{{ route('home') }}#contact">{{ $isBangla ? 'ফ্রি ডেমো বুক করুন' : 'Book a free demo' }} →</a><a class="btn outline" href="mailto:contact@bizzsmart.xyz">{{ $isBangla ? 'কোটেশন চাই' : 'Request a quotation' }}</a></div></div></section>
        <section class="section"><div class="wrap split"><div><h2>{{ $isBangla ? 'আপনার অপারেশন, এক জায়গায়' : 'One connected view of your operation' }}</h2><p class="section-lead">{{ $description }}</p><div class="grid" style="grid-template-columns:1fr 1fr">@foreach($benefits as $benefit)<div class="card"><h3>{{ $benefit['title'] }}</h3><p>{{ $benefit['text'] }}</p></div>@endforeach</div></div><div class="shot"><img src="{{ asset('images/bizzsmart-erp-ecosystem.png') }}" alt="BizzSmart ERP dashboard and connected modules"></div></div></section>
        <section class="section" style="background:#f4f6fb"><div class="wrap"><h2>{{ $isBangla ? 'মূল ফিচার ও বাস্তব workflow' : 'Features that map to real workflows' }}</h2><p class="section-lead">{{ $isBangla ? 'আপনার team-এর প্রয়োজন অনুযায়ী module বেছে নিন; sales, stock, finance ও people একই data ব্যবহার করে।' : 'Choose the modules your team needs today. Sales, stock, finance and people work from the same data foundation.' }}</p><div class="grid">@foreach($page['features'] as $feature)<article class="card"><h3>{{ $feature[0] }}</h3><p>{{ $feature[1] }}</p></article>@endforeach</div></div></section>
        <section class="section"><div class="wrap card" style="background:linear-gradient(120deg,#101f43,#1a3470);color:#fff"><h2 style="color:#fff">{{ $isBangla ? 'Product walkthrough দেখুন' : 'See the product in action' }}</h2><p style="color:#c6d0e6;max-width:700px">{{ $isBangla ? 'আপনার workflow অনুযায়ী live demo বা recorded walkthrough চাইতে পারেন। আমাদের team screen share করে module, report ও implementation plan দেখাবে।' : 'Request a live demo or a recorded walkthrough tailored to your workflow. Our team can show the modules, reports and implementation plan over a screen share.' }}</p><a class="btn" href="{{ route('home') }}#contact">{{ $isBangla ? 'Demo video চাই' : 'Request a demo walkthrough' }} →</a></div></section>
        <section class="section"><div class="wrap split"><div><h2>{{ $isBangla ? 'Pricing ও implementation' : 'Pricing, implementation and support' }}</h2><p class="section-lead">{{ $isBangla ? 'আপনার users, locations ও module অনুযায়ী quotation তৈরি করা হয়। demo-তে workflow, timeline, training এবং support plan পরিষ্কারভাবে দেখানো হবে।' : 'Plans are quoted around your users, locations and selected modules. In a demo we make the workflow, rollout timeline, training and support plan clear.' }}</p><a class="btn" href="{{ route('home') }}#contact">{{ $isBangla ? 'কোটেশন ও implementation plan নিন' : 'Get pricing and an implementation plan' }}</a></div><div class="quote"><strong>{{ $isBangla ? 'Customer proof' : 'Verified customer results' }}</strong><br>{{ $isBangla ? 'বাস্তব customer story ও ফলাফল প্রকাশের আগে customer permission এবং যাচাই করা data ব্যবহার করা হবে। reference চাইলে আমাদের team-এর সঙ্গে কথা বলুন।' : 'We publish customer stories only with permission and verifiable data. Ask our team for references and a tailored walkthrough for your operation.' }}<small>contact@bizzsmart.xyz · +88 01976729816</small></div></div></section>
        <section class="section" style="background:#f4f6fb"><div class="wrap"><h2>{{ $isBangla ? 'সাধারণ প্রশ্ন' : 'Frequently asked questions' }}</h2>@foreach($faqs as $faq)<div class="faq"><h3>{{ $faq['q'] }}</h3><p>{{ $faq['a'] }}</p></div>@endforeach</div></section>
        <section class="bottom-cta"><div class="wrap"><h2>{{ $isBangla ? 'আপনার ব্যবসার জন্য BizzSmart দেখুন' : 'See BizzSmart in your business' }}</h2><p>{{ $isBangla ? 'একটি live demo-তে আপনার workflow নিয়ে আলোচনা করুন।' : 'Bring your workflow to a live demo and get practical answers from the BizzSmart team.' }}</p><a class="btn" href="{{ route('home') }}#contact">{{ $isBangla ? 'ডেমো বুক করুন' : 'Book your free demo' }} →</a></div></section>
    </main>
    <footer class="footer"><div class="wrap">© {{ date('Y') }} BizzSmart · <a href="mailto:contact@bizzsmart.xyz">contact@bizzsmart.xyz</a> · +88 01976729816</div></footer>
</body></html>
