<?php

use App\Http\Controllers\DemoRequestController;
use App\Http\Controllers\AdminController;
use App\Http\Controllers\ProductAssistantController;
use Illuminate\Support\Facades\Route;

$appPath = trim((string) config('app.base_path', ''), '/');

// Keep local sub-folder URLs working while allowing the same app to run at a
// live domain root. Set APP_BASE_PATH=bizzsmart_website locally and leave it
// empty in production.
Route::prefix($appPath)->group(function () {
    Route::get('/', function () {
        return view('home');
    })->name('home');

    Route::post('/request-demo', [DemoRequestController::class, 'store'])
        ->middleware('throttle:6,1')
        ->name('demo.store');

    Route::post('/ask-product-assistant', [ProductAssistantController::class, 'ask'])
        ->middleware('throttle:12,1')
        ->name('product-assistant.ask');
    Route::post('/start-product-assistant', [ProductAssistantController::class, 'start'])
        ->middleware('throttle:6,1')
        ->name('product-assistant.start');
});
$seoPages = [
    'best-erp-software-bangladesh' => [
        'title' => 'Best ERP Software in Bangladesh for Growing Businesses',
        'bn_title' => 'বাংলাদেশের ব্যবসার জন্য সেরা ERP সফটওয়্যার',
        'description' => 'BizzSmart is a connected ERP platform for sales, inventory, finance, HR, payroll and field operations in Bangladesh.',
        'bn_description' => 'BizzSmart বাংলাদেশের sales, inventory, finance, HR, payroll ও field operation একসাথে পরিচালনার connected ERP platform।',
        'intro' => 'Replace disconnected spreadsheets and tools with one practical system for visibility, control and confident growth.',
        'bn_intro' => 'ছড়ানো spreadsheet ও আলাদা software বদলে visibility, control এবং business growth-এর জন্য একটি practical system ব্যবহার করুন।',
        'benefits' => [['Connected modules','One data foundation for every department.'],['Local workflows','Designed around branches, ledgers, dues and field teams.'],['Actionable reports','See sales, stock, cash and people performance quickly.'],['Controlled access','Roles, approvals and audit-friendly records for teams.']],
        'bn_benefits' => [['Connected module','সব department একই data foundation ব্যবহার করে।'],['Local workflow','Branch, ledger, due ও field team-এর workflow-এর জন্য তৈরি।'],['Actionable report','Sales, stock, cash ও people performance দ্রুত দেখুন।'],['নিরাপদ access','Role, approval ও audit-friendly record।']],
        'features' => [['Sales & CRM','Leads, quotations, orders, invoices, customers and collection follow-up.'],['Inventory','Multi-location stock, transfers, adjustments, valuation and reorder visibility.'],['Finance','Bank, cash, journals, receivables, payables and financial reports.'],['HR & payroll','Employees, attendance, leave, salary, advances and performance workflows.'],['Field operations','DSR, routes, commissions, mobile work and branch-level reporting.'],['Dashboards','Real-time management view across business functions.']],
        'faqs' => [['q'=>'Is BizzSmart suitable for Bangladeshi businesses?','a'=>'Yes. The platform is designed for local sales, inventory, accounting, branch, due collection and payroll workflows.'],['q'=>'Can I request a quotation?','a'=>'Yes. Pricing depends on users, locations and selected modules. Contact us for a tailored quotation.'],['q'=>'How does implementation work?','a'=>'We review your workflow, configure modules, import agreed data, train users and provide follow-up support.']],
        'bn_faqs' => [['q'=>'BizzSmart কি বাংলাদেশের ব্যবসার জন্য উপযুক্ত?','a'=>'হ্যাঁ। Local sales, inventory, accounting, branch, due collection ও payroll workflow মাথায় রেখে এটি তৈরি।'],['q'=>'Quotation কি পাওয়া যাবে?','a'=>'হ্যাঁ। User, location ও module অনুযায়ী quotation দেওয়া হয়।'],['q'=>'Implementation কীভাবে হয়?','a'=>'Workflow review, configuration, agreed data import, user training ও follow-up support দেওয়া হয়।']],
    ],
    'retail-pos-software-bangladesh' => ['title'=>'Retail POS Software in Bangladesh','bn_title'=>'বাংলাদেশের জন্য Retail POS Software','description'=>'A retail POS and business management system for fast billing, stock accuracy, customer credit and branch control.','bn_description'=>'দ্রুত billing, stock accuracy, customer credit ও branch control-এর জন্য retail POS ও business management system।','intro'=>'Make every checkout faster while keeping inventory, customer history and financial records connected.','bn_intro'=>'Checkout দ্রুত করুন এবং inventory, customer history ও financial record connected রাখুন।','benefits'=>[['Fast checkout','Capture sales, returns and payments with less friction.'],['Stock accuracy','Every sale updates stock and reporting.'],['Customer credit','Track due, payment history and customer ledgers.'],['Branch control','Compare outlets with consistent permissions and reports.']], 'bn_benefits'=>[['দ্রুত checkout','Sales, return ও payment কম সময়ে record করুন।'],['Stock accuracy','প্রতিটি sale stock ও report update করে।'],['Customer credit','Due, payment history ও customer ledger দেখুন।'],['Branch control','Permission ও report দিয়ে outlet তুলনা করুন।']], 'features'=>[['POS billing','Product search, invoice, discounts, returns and payment recording.'],['Retail inventory','Barcodes, units, stock levels, transfers and adjustments.'],['Customer ledger','Credit sales, collections and statements.'],['Purchasing','Purchase orders, supplier invoices and returns.'],['Promotions','Flexible pricing and sales commission workflows.'],['Reports','Daily sales, product, cashier and outlet reports.']], 'faqs'=>[['q'=>'Does it support multiple retail outlets?','a'=>'Yes. Locations, permissions, stock and reports can be managed across branches.'],['q'=>'Can retail sales work with inventory?','a'=>'Yes. POS transactions and inventory movements use the same records.'],['q'=>'Can I see a demo?','a'=>'Yes. Book a free demo and show us your current retail workflow.']], 'bn_faqs'=>[['q'=>'একাধিক outlet কি manage করা যাবে?','a'=>'হ্যাঁ। Branch, permission, stock ও report একসাথে manage করা যায়।'],['q'=>'POS কি inventory-এর সাথে connected?','a'=>'হ্যাঁ। POS sale এবং inventory movement একই record ব্যবহার করে।'],['q'=>'Demo পাওয়া যাবে?','a'=>'হ্যাঁ। Free demo book করে আপনার workflow দেখান।']]],
    'inventory-management-software' => ['title'=>'Inventory Management Software for Bangladesh','bn_title'=>'বাংলাদেশের জন্য Inventory Management Software','description'=>'Control stock, warehouses, transfers, batches, valuation and reorder decisions with BizzSmart inventory management software.','bn_description'=>'BizzSmart inventory software দিয়ে stock, warehouse, transfer, batch, valuation ও reorder decision control করুন।','intro'=>'Know what is available, where it is, what is moving and what needs attention before it affects sales.','bn_intro'=>'Sales প্রভাবিত হওয়ার আগে জানুন কী available, কোথায় আছে, কী move করছে এবং কী attention চাইছে।','benefits'=>[['Multi-location','Manage godowns, branches and transfers from one view.'],['Batch visibility','Track batches, expiry and quality where relevant.'],['Better decisions','Use movement and valuation reports to plan purchases.'],['Less leakage','Permissions and records improve stock accountability.']], 'bn_benefits'=>[['Multi-location','এক view-তে godown, branch ও transfer manage করুন।'],['Batch visibility','প্রয়োজনে batch, expiry ও quality track করুন।'],['Better decision','Movement ও valuation report দিয়ে purchase plan করুন।'],['কম leakage','Permission ও record stock accountability বাড়ায়।']], 'features'=>[['Item catalog','Categories, variants, units, bundles and pricing-ready records.'],['Stock movement','Receipts, issues, transfers, damages and adjustments.'],['Warehouse controls','Location-level balances and approval workflows.'],['Batch and quality','Batch monitoring, expiry and quality checks.'],['Procurement link','Connect stock levels with purchase planning.'],['Valuation reports','Movement, balance and valuation reports for management.']], 'faqs'=>[['q'=>'Can I manage multiple warehouses?','a'=>'Yes. BizzSmart supports location-aware stock records and transfers.'],['q'=>'Does it support batch tracking?','a'=>'Batch and quality workflows are available where your operation needs them.'],['q'=>'Can it connect inventory to purchasing?','a'=>'Yes. Inventory visibility helps teams plan and control procurement.']], 'bn_faqs'=>[['q'=>'একাধিক warehouse manage করা যাবে?','a'=>'হ্যাঁ। Location-aware stock record ও transfer support করে।'],['q'=>'Batch tracking কি আছে?','a'=>'প্রয়োজন অনুযায়ী batch ও quality workflow ব্যবহার করা যায়।'],['q'=>'Inventory কি purchasing-এর সাথে connected?','a'=>'হ্যাঁ। Inventory visibility দিয়ে procurement plan ও control করা যায়।']]],
    'accounting-payroll-software' => ['title'=>'Accounting and Payroll Software for Bangladesh','bn_title'=>'বাংলাদেশের জন্য Accounting ও Payroll Software','description'=>'Bring bank, cash, journals, receivables, payables, attendance and payroll into one accountable business system.','bn_description'=>'Bank, cash, journal, receivable, payable, attendance ও payroll এক accountable business system-এ আনুন।','intro'=>'Give finance and HR one reliable operating picture—from daily entries to monthly salary and management reporting.','bn_intro'=>'Daily entry থেকে monthly salary ও management report পর্যন্ত finance এবং HR-কে একটি reliable system দিন।','benefits'=>[['Double-entry foundation','Build trustworthy ledgers and financial statements.'],['Payroll control','Calculate salary with attendance, advances and adjustments.'],['Cash visibility','Track deposits, withdrawals, transfers and reconciliation.'],['Audit trail','Keep roles, approvals and history visible.']], 'bn_benefits'=>[['Double-entry foundation','Trustworthy ledger ও financial statement তৈরি করুন।'],['Payroll control','Attendance, advance ও adjustment দিয়ে salary calculate করুন।'],['Cash visibility','Deposit, withdrawal, transfer ও reconciliation track করুন।'],['Audit trail','Role, approval ও history visible রাখুন।']], 'features'=>[['Accounting','Chart of accounts, journals, reversal, trial balance and P&L.'],['Bank and cash','Accounts, reconciliation, deposits, withdrawals and transfers.'],['Payroll','Grades, salary, overtime, advances, bonuses and payments.'],['Attendance','Shifts, rosters, leave, holidays and overtime.'],['Receivables','Customer dues, collections and statements.'],['Reports','Finance, payroll, expense and management reporting.']], 'faqs'=>[['q'=>'Does it include payroll?','a'=>'Yes. Payroll can use salary grades, attendance, overtime, advances and adjustments.'],['q'=>'Can the finance team control bank and cash?','a'=>'Yes. Bank, cash, deposits, withdrawals, transfers and reconciliation are included.'],['q'=>'Is there implementation support?','a'=>'Yes. We help configure the workflow, train users and provide follow-up support.']], 'bn_faqs'=>[['q'=>'Payroll কি included?','a'=>'হ্যাঁ। Salary grade, attendance, overtime, advance ও adjustment ব্যবহার করা যায়।'],['q'=>'Bank ও cash control করা যাবে?','a'=>'হ্যাঁ। Deposit, withdrawal, transfer ও reconciliation included।'],['q'=>'Implementation support আছে?','a'=>'হ্যাঁ। Workflow configure, user training ও follow-up support দেওয়া হয়।']]],
    'manufacturing-erp' => ['title'=>'Manufacturing ERP for Production and Quality Control','bn_title'=>'Production ও Quality Control-এর জন্য Manufacturing ERP','description'=>'Plan production, batches, materials, resources, quality and cost with BizzSmart manufacturing ERP.','bn_description'=>'BizzSmart manufacturing ERP দিয়ে production, batch, material, resource, quality ও cost plan করুন।','intro'=>'Connect production planning to materials, people, quality and financial visibility without losing operational detail.','bn_intro'=>'Operational detail না হারিয়ে production planning-কে material, people, quality ও financial visibility-এর সাথে connect করুন।','benefits'=>[['Plan confidently','Use BOM, batches and schedules to organize production.'],['Control materials','Track consumption, availability and movement.'],['Protect quality','Record checks, yields and batch outcomes.'],['Know cost','Bring labor, material and batch expenses into view.']], 'bn_benefits'=>[['Confident planning','BOM, batch ও schedule দিয়ে production organize করুন।'],['Material control','Consumption, availability ও movement track করুন।'],['Quality protect','Check, yield ও batch outcome record করুন।'],['Cost visibility','Labor, material ও batch expense দেখুন।']], 'features'=>[['BOM and batches','Templates, bills of materials and batch records.'],['Production schedule','Plan jobs, resources and expected output.'],['Material consumption','Track issues and consumption against production.'],['Quality control','Record inspections, yield and exceptions.'],['Labor and cost','Capture work and production-related expense.'],['Reports','Production, batch, inventory and cost reporting.']], 'faqs'=>[['q'=>'Can it support batch production?','a'=>'Yes. Batch templates, BOM, schedules, consumption and quality workflows are supported.'],['q'=>'Can manufacturing connect to inventory?','a'=>'Yes. Material consumption and output can flow through inventory records.'],['q'=>'How do we start implementation?','a'=>'We map your production flow first, then configure modules and train the responsible team.']], 'bn_faqs'=>[['q'=>'Batch production support করে?','a'=>'হ্যাঁ। Batch template, BOM, schedule, consumption ও quality workflow আছে।'],['q'=>'Manufacturing কি inventory-এর সাথে connected?','a'=>'হ্যাঁ। Material consumption ও output inventory record-এ আসে।'],['q'=>'Implementation কীভাবে শুরু হবে?','a'=>'প্রথমে production flow map করে module configure ও team training করা হয়।']]],
    'restaurant-filling-station-management' => ['title'=>'Restaurant and Filling Station Management Software','bn_title'=>'Restaurant ও Filling Station Management Software','description'=>'Manage tables, kitchen orders, billing, pumps, tanks, shifts, credit sales and reconciliation with BizzSmart.','bn_description'=>'BizzSmart দিয়ে table, kitchen order, billing, pump, tank, shift, credit sale ও reconciliation manage করুন।','intro'=>'Use industry-ready workflows for restaurants and filling stations while keeping finance, inventory and reporting connected.','bn_intro'=>'Restaurant ও filling station-এর industry-ready workflow ব্যবহার করুন, finance, inventory ও report connected রেখে।','benefits'=>[['Restaurant flow','Connect table orders, kitchen and billing.'],['Station control','Track shifts, tanks, pumps, nozzles and reconciliation.'],['Credit visibility','Manage credit sales, parties and collections.'],['Management view','Compare shifts, outlets, sales and expenses.']], 'bn_benefits'=>[['Restaurant flow','Table order, kitchen ও billing connect করুন।'],['Station control','Shift, tank, pump, nozzle ও reconciliation track করুন।'],['Credit visibility','Credit sale, party ও collection manage করুন।'],['Management view','Shift, outlet, sales ও expense compare করুন।']], 'features'=>[['Table management','Tables, orders, kitchen display and bill generation.'],['Station operations','Tanks, pumps, nozzles, shifts and cart reconciliation.'],['Credit sales','Credit bills, parties, dues and payment history.'],['Inventory','Ingredients, products, stock movement and purchasing.'],['Staff workflows','Roles, attendance, shifts and permissions.'],['Reports','Daily closeout, sales, stock and finance reports.']], 'faqs'=>[['q'=>'Does it support restaurant tables and kitchen?','a'=>'Yes. Table management, order taking, kitchen display and billing workflows are available.'],['q'=>'Can filling station shifts be reconciled?','a'=>'Yes. Shift, tank, pump, nozzle and cart reconciliation workflows are supported.'],['q'=>'Can I request a quotation for both businesses?','a'=>'Yes. Contact us with your locations and workflow for a tailored quotation.']], 'bn_faqs'=>[['q'=>'Restaurant table ও kitchen support করে?','a'=>'হ্যাঁ। Table, order, kitchen display ও billing workflow আছে।'],['q'=>'Filling station shift reconcile করা যাবে?','a'=>'হ্যাঁ। Shift, tank, pump, nozzle ও cart reconciliation support করে।'],['q'=>'দুই business-এর quotation চাইতে পারি?','a'=>'হ্যাঁ। Location ও workflow পাঠালে tailored quotation দেওয়া হবে।']],
    ],
];

Route::prefix($appPath)->group(function () use ($seoPages) {
Route::get('/sitemap.xml', function () use ($seoPages) {
    $urls = [route('home')];
    foreach (array_keys($seoPages) as $slug) {
        $urls[] = route('seo.'.$slug);
        $urls[] = route('seo.bn.'.$slug);
    }
    $xml = '<?xml version="1.0" encoding="UTF-8"?>'."\n".'<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">';
    foreach ($urls as $url) $xml .= '<url><loc>'.e($url).'</loc><changefreq>monthly</changefreq></url>';
    return response($xml.'</urlset>', 200, ['Content-Type' => 'application/xml; charset=UTF-8']);
})->name('sitemap');

foreach ($seoPages as $slug => $page) {
    Route::get('/'.$slug, fn () => view('seo.landing', compact('page', 'slug') + ['locale' => 'en']))->name('seo.'.$slug);
    Route::get('/bn/'.$slug, fn () => view('seo.landing', compact('page', 'slug') + ['locale' => 'bn']))->name('seo.bn.'.$slug);
}
});

Route::prefix(($appPath ? $appPath.'/' : '').'admin')->name('admin.')->group(function () {
    Route::get('/login', [AdminController::class, 'login'])->name('login');
    Route::post('/login', [AdminController::class, 'authenticate'])->name('authenticate');

    Route::middleware('bizzsmart.admin')->group(function () {
        Route::get('/', [AdminController::class, 'dashboard'])->name('dashboard');
        Route::get('/assistant-conversations', [AdminController::class, 'assistantConversations'])->name('assistant-conversations');
        Route::get('/maintenance/clear-cache', [AdminController::class, 'clearCaches'])->name('maintenance.clear-cache');
        Route::delete('/requests/{demoRequest}', [AdminController::class, 'destroy'])->name('requests.destroy');
        Route::post('/logout', [AdminController::class, 'logout'])->name('logout');
    });
});
